

def custom_sort(t, s):
    q, q2 = [], []
    for char in s:
        if char in t:
            q.insert(0, char)
        else:
            q2.insert(0, char)
    q = "".join(sorted(q, key=t.index))
    q2 = "".join(sorted(q2))
    return q + q2


class Test:
    def assert_equals(a, b):
        try:
            assert a == b
        except AssertionError:
            print(f"{a}\n > should equal \n\t{b}")


TestsConsoleTest = Test


Test.assert_equals(custom_sort("edc", "abcdefzyx"), "edcabfxyz")
Test.assert_equals(custom_sort("fby", "abcdefzyx"), "fbyacdexz")
Test.assert_equals(custom_sort("", "abcdefzyx"), "abcdefxyz")
Test.assert_equals(custom_sort("", ""), "")
Test.assert_equals(custom_sort('cteqh', 'xnjanztmhg'), "thagjmnnxz")
Test.assert_equals(custom_sort('jv', 'cxkafinfiuhnnaracsztbrcwaifwattzavwohoqskauififucq'),
                   "vaaaaaaabccccfffffhhiiiiikknnnooqqrrsstttuuuwwwxzz")
Test.assert_equals(custom_sort('xtz', 'uhgpqydzwtsemucfidpvrvormgfjefpqeprvmyiazqokmnhdwvyglngcsriw'),
                   "tzzaccdddeeefffgggghhiiijklmmmmnnooppppqqqrrrrssuuvvvvwwwyyy")
Test.assert_equals(custom_sort(
    'eyuti', 'iuanyojxqbmihzyvjunb'), "yyuuiiabbhjjmnnoqvxz")
Test.assert_equals(custom_sort(
    'ndgi', 'eqfbnjbpbisjoakfnncpaphvvzxsodaw'), "nnndiaaabbbceffhjjkoopppqssvvwxz")
Test.assert_equals(custom_sort('ymd', 'duoisjfobwlztxsaymzjwvpofouyijglwgvogpt'),
                   "yymdabffgggiijjjlloooooppssttuuvvwwwxzz")
Test.assert_equals(custom_sort('wpkmv', 'crcasndkumqcckmqxcpagkjveovcmnmzvbkixeduqohkutbelm'),
                   "pkkkkkmmmmmvvvaabbccccccddeeeghijlnnooqqqrstuuuxxz")
Test.assert_equals(custom_sort('qdmbfc', 'mruwsotaydpzeezpgmmcrhbwsihrbzryqheigapvaehnyjgvbvqrdxtqkczujzqngpdmrduffcokcnfcqqmqtwbquzssalydifip'),
                   "qqqqqqqqdddddmmmmmbbbbffffcccccaaaaeeeegggghhhhiiiijjkklnnnooppppprrrrrrsssstttuuuuvvvwwwxyyyyzzzzzz")
Test.assert_equals(custom_sort('iupmz', 'ixavjrmbwacgwvxcrauvcfcizfoxxabdyossqvzubqnpdzphbpurikqzqigjdrjsycpjlpstokvnijpcchcgtdfvqkltbdqidptvbsmwxeuqxyvcyzfiksnrrzbpmxdlhzieocmabqszqanfwjqmjb'),
                   "iiiiiiiiuuuuppppppppmmmmmzzzzzzzzaaaaaabbbbbbbbbccccccccccdddddddeefffffggghhhjjjjjjjkkkklllnnnnooooqqqqqqqqqqrrrrrrsssssssttttvvvvvvvvwwwwxxxxxxxyyyy")
Test.assert_equals(custom_sort('cjhfnu', 'uokmxyzaisghuqmxxhnntlhhasjwfkjutdoumlkwfusscjspauroihkxmsvamxuqronfszjmgnqjlwdkvndslsykrojvrienrhtrvtrmacuneouorbjceadhskonhbnghctqbqkgzqwuaegumugggilhjbzqcpgbpkfxlbeyinfdrzkvesxjnmyvrwbftuymtzrzzzlm'),
                   "cccccjjjjjjjjjhhhhhhhhhhffffffnnnnnnnnnnnuuuuuuuuuuuuuaaaaaaabbbbbbbdddddeeeeeegggggggggiiiiikkkkkkkkkklllllllmmmmmmmmmmmoooooooopppqqqqqqqrrrrrrrrrrrssssssssssstttttttvvvvvvwwwwwxxxxxxxyyyyyzzzzzzzzz")
Test.assert_equals(custom_sort('novctmix', 'hufppxpeisstygylmfwgfftwagpnkzqzcizntyejrvsfxxavvezdsddcdkgogkgkqkuexycbqzdicpxdqjdyncgmiatdbshrzcdfmxyanudnynwdhunfjqqccnncolkpcylkivehdaejlndoldmwbtibzcfsvpvmbyweviedadrqjnukmemjbwpefwhuonpdysivbeybmejzcjmswrpmgieffmpsfxkmmojklnqpelfrcaojcpouzkctajfwvgddcflfksscuwopqrjyqwghnwgblavhztnaeyqgebjodyte'),
                   "nnnnnnnnnnnnnnnooooooooovvvvvvvvvvcccccccccccccccccttttttttmmmmmmmmmmmmmiiiiiiiiixxxxxxxaaaaaaaaaabbbbbbbbbbddddddddddddddddddddeeeeeeeeeeeeeeeeeffffffffffffffffgggggggggggghhhhhhhjjjjjjjjjjjjjkkkkkkkkkkkklllllllllppppppppppppppqqqqqqqqqqqrrrrrrsssssssssssuuuuuuuuwwwwwwwwwwwwyyyyyyyyyyyyyyzzzzzzzzzz")
Test.assert_equals(custom_sort('thvuybo', 'ahharlbhljltdsfdnosejlfqjiagscjzaeohishxlclidyjwujukzjosfnwafvpmifsuuefnxgxjptayqqdidesuxbdbeljravainxgqddujcrwgawdqrhzoesozymihqktdkbhwmtxyoaawgilobdpfdissmmbomfzmogjnrbwrtwaxditdnivjfajpfuoozoyaplurcmodmtfvlnxmhhmygtpxgaxsgfpynppmjbklckosakqejqcmmhbaagpwryflomemizdlfcecslcqdtwyjjksavdbzimziqiloagxebqygirghyjmiaxzyoweadutohctkmwruxpnobfoglrksfxxyk'),
                   "ttttttttttthhhhhhhhhhhhhvvvvvuuuuuuuuuuyyyyyyyyyyyyybbbbbbbbbbbbooooooooooooooooooooaaaaaaaaaaaaaaaaaaaaaaccccccccccdddddddddddddddddddeeeeeeeeeeeffffffffffffffffggggggggggggggiiiiiiiiiiiiiiiiijjjjjjjjjjjjjjjjjjkkkkkkkkkkllllllllllllllllmmmmmmmmmmmmmmmmmmmnnnnnnnnnpppppppppppqqqqqqqqqqqrrrrrrrrrrrssssssssssssssswwwwwwwwwwwwxxxxxxxxxxxxxxxzzzzzzzzzz")
Test.assert_equals(custom_sort('pgjiyhkor', 'ctocsybgtvhbobisqhxicddaiykrlyfzegnmytpuomrwybvaqcuigzehqnizepqjyamnraqprghctzxdgufqrwjfskjfyonwtbqhtjnhtqzarwawjprdckbezvvolbtcrubnpvstaaiytphclyfzxrajvailyvhnxjrwarccndmefmygpkjlurgnrijyfglcicvfgysgptqlnuqfybscgjqbufiqzpixerftznkixownsmmoqhhcfuacwmahcuxgnvvawzktcjzyofmpxbgxrmjeabkknkbkterkaqdtrekmfoleyhikdcnwnkiyacxquhyvuwdrralwypvbwmhorsvoghtjnsavtbiefeif'),
                   "pppppppppppggggggggggggggjjjjjjjjjjjjjiiiiiiiiiiiiiiiiyyyyyyyyyyyyyyyyyyyhhhhhhhhhhhhhhhkkkkkkkkkkkkkkooooooooooorrrrrrrrrrrrrrrrrrrraaaaaaaaaaaaaaaaaaabbbbbbbbbbbbbbbcccccccccccccccccccddddddddeeeeeeeeeeeefffffffffffffffflllllllllmmmmmmmmmmmmnnnnnnnnnnnnnnnnnqqqqqqqqqqqqqqqssssssssstttttttttttttttttuuuuuuuuuuuvvvvvvvvvvvvvvwwwwwwwwwwwwwxxxxxxxxxxzzzzzzzzzzz")
Test.assert_equals(custom_sort('jxrqklbgut', 'qdjufpwzuttywfbcviuyreqgmwlnejsgbapgbybohkyflajcmhikdpzszwbsmfgcbhmtxwofgjjkvcednyyphusnzvahpeaoqsshhgjslpybwzambbuwbkpnkrnpmetqfuytmhbrousmsuuinvnrlmerfdunixycgmtslmrervxmsekkrdcznyykghhdzmhwnzycqxwzolqnswwmukpxikuklwqqhkgxlknqjtpigvoivwnymxxjmikvklafgkibreppwwkwffxixgjxheyornboevxnqslwpxjeaagqvcdhytirdxyaypghxbqpodwrrgyovsgcjrealijagpeiklkbzlpskkratjnoowdpunvfdmgjsitasevwjxrnyjoexhhgrgizoyszuzosaaxugpaopkpqrpkxbchygmovixndcggrvnjxazuphbztcumvntlqrxihojlkiwydtabdnhxjedbnircuwzbbikguyjucwuqwvohb'),
                   "jjjjjjjjjjjjjjjjjjjjxxxxxxxxxxxxxxxxxxxxxxxrrrrrrrrrrrrrrrrrrrrrqqqqqqqqqqqqqqqkkkkkkkkkkkkkkkkkkkkkkkkklllllllllllllllbbbbbbbbbbbbbbbbbbbbbbggggggggggggggggggggggggguuuuuuuuuuuuuuuuuuuuutttttttttttttaaaaaaaaaaaaaaaaaaccccccccccccccdddddddddddddddeeeeeeeeeeeeeeeeefffffffffffhhhhhhhhhhhhhhhhhhhhhhiiiiiiiiiiiiiiiiiiiimmmmmmmmmmmmmmmmmmmnnnnnnnnnnnnnnnnnnnnnnnooooooooooooooooooopppppppppppppppppppppppsssssssssssssssssssvvvvvvvvvvvvvvvvvwwwwwwwwwwwwwwwwwwwwwwwwyyyyyyyyyyyyyyyyyyyyyyyzzzzzzzzzzzzzzzz")
Test.assert_equals(custom_sort('vupdsfgrxkob', 'qqxaqgcnyxpskszwdgcfziyhamuursywnpyagjeffyiiduegqxyjvjgbifixwlrcdhhlnviurfuwqzdvoxqlrxhzncaovazhsiovnutkroznckeuawhlamsvvpmrvpdnovzmtrnyohgybsemqzcxlcwryqfeseqxkqqdqqhholzssrqsrnswqgqteajockivqqkjmmafdkswbduaelhqqbmslrygrudswaziadrdwfmicnmdtmrwgxmuxipmnjbhdobbknepdewivqwnfdxnkzdzdtgcbafvjgaolbptzfjexjkbgrsajmcgyeivgneyyltfgaeqgzzmtfkkokfhwdhvmhhemcnfngjgjupjgcwtmtzuuvsexrhbzqxlfwfyeswevyetwpwmfvmhwrvgjxbgkarinrqavoeeujkthnoimatblovywbkjkwqijkkxizlrpqqsmqwaitwrgmrxcaipshowtkmecmigwufqsqxbjdyntvcpgfqcbmnjlvvftecppcdfecsbkulqozslpybgzfuyjlfldokvrkeqikxjpszdtoebwwekbfemrxlbcqsvpopzqabixdrhfeyiqtkh'),
                   "vvvvvvvvvvvvvvvvvvvvvvvvvuuuuuuuuuuuuuuuuuppppppppppppppppppdddddddddddddddddddddddssssssssssssssssssssssssffffffffffffffffffffffffffgggggggggggggggggggggggggrrrrrrrrrrrrrrrrrrrrrrrrrxxxxxxxxxxxxxxxxxxxxxkkkkkkkkkkkkkkkkkkkkkkkkkkooooooooooooooooooobbbbbbbbbbbbbbbbbbbbbbaaaaaaaaaaaaaaaaaaaaaaccccccccccccccccccccceeeeeeeeeeeeeeeeeeeeeeeeeeeeehhhhhhhhhhhhhhhhhhhhhiiiiiiiiiiiiiiiiiiiiiiijjjjjjjjjjjjjjjjjjjjjlllllllllllllllllllmmmmmmmmmmmmmmmmmmmmmmmmmmmnnnnnnnnnnnnnnnnnnnnnqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqtttttttttttttttttttwwwwwwwwwwwwwwwwwwwwwwwwwwwwyyyyyyyyyyyyyyyyyyyyzzzzzzzzzzzzzzzzzzzzzz")
Test.assert_equals(custom_sort('opdzsivgarylwut', 'alvvrdrpodmnqtlvmzbacxvxdmewsianihbdhnbiwhdzxnpkzvanawjkcqszvlslhxuanzdswpfvutldiwvskctbxzapqjvrfnymebzvqmvprtrmjgngzwpcdxmjkvbfuzyjrlvyizvbqcffjizgcyqkggzocifneiwkcwvdxzhdrjcrnrjdugnhzfpnmoxbczbqrupyyrumlbetwzaualwykciqxllxuermbdphxjwprprvmehowzxtyagrlezarcxwywgezsxxnwxdrmwoaakksfxipklmghcxltsncwqwnivztepxgjnwhizufgfakswgcqykysqiucwveponhvunirxwtmafbfrugnntjhadqggnerfkxfpipxpxeruauaaexvzxsonopkxeaxmachfxjjdtoxutrqvgydvevtjwltkxeiggxkhbecsqigqfqjqazfncbgxalbzsxpksvlvtqqwcvnqpvnqvfqqnufdojpjomsbpalfnwbrtdvhetvxdjpnxoftlplthcdfgzlzqsdooiacopqsjumjmnbqeuspusrpbpxnxgfxnqdlstxmfczqburziytvkcxdskkzkrisxycrtlpaathgiligmgywbnmynkumhmovagynbrlvljubifkwivrqhsykamixhhvdfngauifhwpkziutxqoqngsjbjcklrultvjshkmpmlchflzpgmvgrzkqsrxmicikvbgbzmmypzzbcndxjpqejhhktvngzqtlwiuhqjnanqqpgnlfvogchjzsqwtsdwljqvjqazhpuhxyhwzpofembzxdofktxeozijzfocewsojmrpgcamplqfsdxbognpdtkxpogqanlvzmicgfrnkgwwwvsxfpaywesmysmqqsny'),
                   "oooooooooooooooooooooooooppppppppppppppppppppppppppppppppppppppppppdddddddddddddddddddddddddddddzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzssssssssssssssssssssssssssssssssssiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiivvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvgggggggggggggggggggggggggggggggggggggggaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaarrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrryyyyyyyyyyyyyyyyyyyyyyyllllllllllllllllllllllllllllllllllwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwuuuuuuuuuuuuuuuuuuuuuuuuuuuttttttttttttttttttttttttttttttbbbbbbbbbbbbbbbbbbbbbbbbbbbbbccccccccccccccccccccccccccccccccceeeeeeeeeeeeeeeeeeeeeeeefffffffffffffffffffffffffffffffffffhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx")
